In [1]:
#Jeffrey LinkedIn Data Analysis

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import seaborn as sns

In [5]:
df = pd.read_csv('dux-soup-visit-data@2021-04-15 09h45.csv')

In [6]:
df

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
0,id.46671796,2021/04/08 15:00:43,https://www.linkedin.com/in/mattroconnor,https://www.linkedin.com/sales/people/ACwAAALI...,https://media-exp1.licdn.com/dms/image/C5103AQ...,1,Matt,O,Connor,14034,...,https://www.pulley.ai/,,,,,"New York, New York, United States",Computer Software,sent road map article|Sent sales process blog,NaN,NaN
1,id.348628649,2021/04/08 15:02:06,https://www.linkedin.com/in/sophiaononye,https://www.linkedin.com/sales/people/ACwAABTH...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Sophia,Ononye-Onyia,Mph,13702,...,https://sophiaconsultingfirm.com/,sophia@sophiaconsultingfirm.com,347-851-8674,,drsophiao,"New York, New York, United States",Management Consulting,sent road map article|Sent sales process blog,NaN,NaN
2,id.7426653,2021/04/08 15:03:29,https://www.linkedin.com/in/sanjeevthohan,https://www.linkedin.com/sales/people/ACwAAABx...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Sanjeev,,Thohan,13363,...,http://www.kinnate.com,drtox@hotmail.com,,,,"San Diego County, California, United States",Biotechnology,sent road map article|Sent sales process blog,NaN,NaN
3,id.115376758,2021/04/08 15:04:51,https://www.linkedin.com/in/mpavichal,https://www.linkedin.com/sales/people/ACwAAAbg...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Mishal,Avichal Mbs,Activate,4245,...,https://www.atreyadigitalhealth.com/,mavichal@atreyadigitalhealth.com,(201) 716-9693,,,New York City Metropolitan Area,Pharmaceuticals,Sent sales process blog,NaN,NaN
4,id.25334198,2021/04/08 15:06:12,https://www.linkedin.com/in/alan-teitel-bb25988,https://www.linkedin.com/sales/people/ACwAAAGC...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Alan,,Teitel,17455,...,,alan@alcovepro.com,516-413-7900,,UltraSlo,New York City Metropolitan Area,Media Production,sent road map article|Sent sales process blog,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,id.5873951,2021/04/14 18:23:32,https://www.linkedin.com/in/arthur-besteman-33...,https://www.linkedin.com/sales/people/ACwAAABZ...,https://media-exp1.licdn.com/dms/image/C5603AQ...,2,Arthur,,Besteman,267,...,http://www.avemacontractservices.com,,,,,"Miami, Florida, United States",Pharmaceuticals,|🦆-default-invited,NaN,NaN
575,id.366773516,2021/04/14 18:24:57,https://www.linkedin.com/in/digant-bodawala-23...,https://www.linkedin.com/sales/people/ACwAABXc...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,Digant,,Bodawala,1174,...,http://www.enterisbiopharma.com,,,,,"Whippany, New Jersey, United States",Biotechnology,|🦆-default-invited,NaN,NaN
576,id.29173239,2021/04/14 18:26:23,https://www.linkedin.com/in/william-chatoff-7b...,https://www.linkedin.com/sales/people/ACwAAAG9...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,William,,Chatoff,964,...,https://edgepharma.com,,,,EdgePharmacyRx,"Hinesburg, Vermont, United States",Hospital & Health Care,|🦆-default-invited,NaN,NaN
577,id.611156261,2021/04/14 18:27:49,https://www.linkedin.com/in/mikado-koie-485812150,https://www.linkedin.com/sales/people/ACwAACRt...,https://media-exp1.licdn.com/dms/image/C5603AQ...,3,Mikado,,Koie,56,...,http://www.cmiccmousa.com,,,,,"Cranbury, New Jersey, United States",Pharmaceuticals,|🦆-default-invited,NaN,NaN
578,id.17972945,2021/04/14 18:29:17,https://www.linkedin.com/in/deborah-kaldunski-...,https://www.linkedin.com/sales/people/ACwAAAES...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,2,Deborah,Kaldunski,Cole,677,...,http://www.primera-corp.com,,,,,San Francisco Bay Area,Primary/Secondary Education,|🦆-default-invited,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 579 entries, 0 to 578
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              579 non-null    object
 1   VisitTime       579 non-null    object
 2   Profile         579 non-null    object
 3   SalesProfile    579 non-null    object
 4   Picture         579 non-null    object
 5   Degree          579 non-null    int64
 6   First Name      579 non-null    object
 7   Middle Name     579 non-null    object
 8   Last Name       579 non-null    object
 9   Connections     579 non-null    int64
 10  Summary         579 non-null    object
 11  From            579 non-null    object
 12  Title           579 non-null    object
 13  Company         579 non-null    object
 14  CompanyProfile  579 non-null    object
 15  CompanyWebsite  579 non-null    object
 16  Email           579 non-null    object
 17  Phone           579 non-null    object
 18  IM              579 non-null    object
 19  Twitter         579 non-null    object
 20  Location        579 non-null    object
 21  Industry        579 non-null    object
 22  My Tags         579 non-null    object
 23  My Notes        0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
dtypes: float64(2), int64(2), object(21)
memory usage: 113.2+ KB

In [8]:
df.sample()

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
293,id.23188290,2021/04/12 16:01:21,https://www.linkedin.com/in/sam-miller-1969237,https://www.linkedin.com/sales/people/ACwAAAFh...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Sam,,Miller,5347,...,http://www.proteusmotion.com,sam@proteusmotion.com,781.910.7489,,,"New York, New York, United States","Health, Wellness and Fitness",sent road map article|Sent promote or fire art...,NaN,NaN

In [9]:
First=df['Degree']==1

In [10]:
First

0       True
1       True
2       True
3       True
4       True
       ...
574    False
575    False
576    False
577    False
578    False
Name: Degree, Length: 579, dtype: bool

In [11]:
first=df[First]

In [12]:
first

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,CompanyWebsite,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24
0,id.46671796,2021/04/08 15:00:43,https://www.linkedin.com/in/mattroconnor,https://www.linkedin.com/sales/people/ACwAAALI...,https://media-exp1.licdn.com/dms/image/C5103AQ...,1,Matt,O,Connor,14034,...,https://www.pulley.ai/,,,,,"New York, New York, United States",Computer Software,sent road map article|Sent sales process blog,NaN,NaN
1,id.348628649,2021/04/08 15:02:06,https://www.linkedin.com/in/sophiaononye,https://www.linkedin.com/sales/people/ACwAABTH...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Sophia,Ononye-Onyia,Mph,13702,...,https://sophiaconsultingfirm.com/,sophia@sophiaconsultingfirm.com,347-851-8674,,drsophiao,"New York, New York, United States",Management Consulting,sent road map article|Sent sales process blog,NaN,NaN
2,id.7426653,2021/04/08 15:03:29,https://www.linkedin.com/in/sanjeevthohan,https://www.linkedin.com/sales/people/ACwAAABx...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Sanjeev,,Thohan,13363,...,http://www.kinnate.com,drtox@hotmail.com,,,,"San Diego County, California, United States",Biotechnology,sent road map article|Sent sales process blog,NaN,NaN
3,id.115376758,2021/04/08 15:04:51,https://www.linkedin.com/in/mpavichal,https://www.linkedin.com/sales/people/ACwAAAbg...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Mishal,Avichal Mbs,Activate,4245,...,https://www.atreyadigitalhealth.com/,mavichal@atreyadigitalhealth.com,(201) 716-9693,,,New York City Metropolitan Area,Pharmaceuticals,Sent sales process blog,NaN,NaN
4,id.25334198,2021/04/08 15:06:12,https://www.linkedin.com/in/alan-teitel-bb25988,https://www.linkedin.com/sales/people/ACwAAAGC...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Alan,,Teitel,17455,...,,alan@alcovepro.com,516-413-7900,,UltraSlo,New York City Metropolitan Area,Media Production,sent road map article|Sent sales process blog,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,id.65853043,2021/04/14 15:54:10,https://www.linkedin.com/in/tyron-dew-4970791a,https://www.linkedin.com/sales/people/ACwAAAPs...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Tyron,,Dew,89,...,http://www.genewiz.com,dew.tyron@yahoo.com,919-400-0318,,,"Raleigh, North Carolina, United States",Consumer Services,🦆-default-invited|Sent sales process blog,NaN,NaN
526,id.20478405,2021/04/14 15:55:32,https://www.linkedin.com/in/edward-morris-b19a366,https://www.linkedin.com/sales/people/ACwAAAE4...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Edward,,Morris,1274,...,,edward@lynxworkflow.com,,,EdCanary,"Syracuse, New York, United States",Research,sent road map article|Sent promote or fire art...,NaN,NaN
527,id.161171344,2021/04/14 15:56:53,https://www.linkedin.com/in/rachaelstults,https://www.linkedin.com/sales/people/ACwAAAmb...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Rachael,,Stults,39,...,https://www.bioclinica.com,stultsrachael@yahoo.com,,,,Greater Philadelphia,Pharmaceuticals,🦆-default-invited|Sent sales process blog,NaN,NaN
528,id.123443746,2021/04/14 15:58:15,https://www.linkedin.com/in/stephen-daire-42a4...,https://www.linkedin.com/sales/people/ACwAAAdb...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Stephen,,Daire,1526,...,https://proteanindustries.com/,sadaire@proteangistsolutions.com,6072875991,,DhDair,New York City Metropolitan Area,Think Tanks,|🦆-default-invited|sent road map article|Sent ...,NaN,NaN
529,id.182513148,2021/04/14 15:59:38,https://www.linkedin.com/in/carey-camacho-0501...,https://www.linkedin.com/sales/people/ACwAAArg...,,1,Carey,,Camacho,174,...,http://www.techinst.com,carey@microtechsol.com,650-651-3076,,,"Burlingame, California, United States",Biotechnology,|🦆-default-invited|Sent sales process blog,NaN,NaN

In [13]:
cities=first.groupby('Location')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(10)

In [14]:
cities

                                        Location  count
120            New York, New York, United States     89
119              New York City Metropolitan Area     83
64                                Greater Boston     28
153         San Diego, California, United States     16
19          Boston, Massachusetts, United States     13
152  San Diego County, California, United States     12
70                          Greater Philadelphia     10
26             Brooklyn, New York, United States      7
181                                United States      7
154                       San Francisco Bay Area      7

In [27]:
industry=first.groupby('Industry')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(10)

In [28]:
industry

                               Industry  count
47                      Pharmaceuticals    138
3                         Biotechnology    133
30  Information Technology and Services     35
38            Marketing and Advertising     30
9                     Computer Software     14
26               Hospital & Health Care     14
36                Management Consulting     14
55                             Research     10
60     Venture Capital & Private Equity      9
31                             Internet      8

In [17]:
title=first.groupby('Title')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(10)

In [18]:
title

                 Title  count
143            Founder     30
144      Founder & CEO     19
222              Owner     17
208  Managing Director     10
76          Co-Founder     10
159    Founder and CEO     10
229          President      9
225            Partner      8
79    Co-Founder & CEO      7
31                 CEO      7

In [19]:
company=first.groupby('Company')['Degree'] \
                             .count() \
                             .reset_index(name='count') \
                             .sort_values(['count'], ascending=False) \
                             .head(10)

In [20]:
company

                                     Company  count
61                                Bioclinica     32
151                                GenScript     17
147  GENEWIZ, A Brooks Life Sciences Company     12
342        Sharp, part of UDG Healthcare plc     10
146                                  GENEWIZ      8
111                                  Detect       4
324                           SCYNEXIS, Inc.      3
357        Spectrix Analytical Services, LLC      3
433                             millermedia7      2
181       Innovative Science Solutions, Inc.      2

In [21]:
first['Tags'] = first['My Tags'].str.split('|',expand=False)

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [22]:
first

,id,VisitTime,Profile,SalesProfile,Picture,Degree,First Name,Middle Name,Last Name,Connections,...,Email,Phone,IM,Twitter,Location,Industry,My Tags,My Notes,Unnamed: 24,Tags
0,id.46671796,2021/04/08 15:00:43,https://www.linkedin.com/in/mattroconnor,https://www.linkedin.com/sales/people/ACwAAALI...,https://media-exp1.licdn.com/dms/image/C5103AQ...,1,Matt,O,Connor,14034,...,,,,,"New York, New York, United States",Computer Software,sent road map article|Sent sales process blog,NaN,NaN,"[sent road map article, Sent sales process blog]"
1,id.348628649,2021/04/08 15:02:06,https://www.linkedin.com/in/sophiaononye,https://www.linkedin.com/sales/people/ACwAABTH...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Sophia,Ononye-Onyia,Mph,13702,...,sophia@sophiaconsultingfirm.com,347-851-8674,,drsophiao,"New York, New York, United States",Management Consulting,sent road map article|Sent sales process blog,NaN,NaN,"[sent road map article, Sent sales process blog]"
2,id.7426653,2021/04/08 15:03:29,https://www.linkedin.com/in/sanjeevthohan,https://www.linkedin.com/sales/people/ACwAAABx...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Sanjeev,,Thohan,13363,...,drtox@hotmail.com,,,,"San Diego County, California, United States",Biotechnology,sent road map article|Sent sales process blog,NaN,NaN,"[sent road map article, Sent sales process blog]"
3,id.115376758,2021/04/08 15:04:51,https://www.linkedin.com/in/mpavichal,https://www.linkedin.com/sales/people/ACwAAAbg...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Mishal,Avichal Mbs,Activate,4245,...,mavichal@atreyadigitalhealth.com,(201) 716-9693,,,New York City Metropolitan Area,Pharmaceuticals,Sent sales process blog,NaN,NaN,[Sent sales process blog]
4,id.25334198,2021/04/08 15:06:12,https://www.linkedin.com/in/alan-teitel-bb25988,https://www.linkedin.com/sales/people/ACwAAAGC...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Alan,,Teitel,17455,...,alan@alcovepro.com,516-413-7900,,UltraSlo,New York City Metropolitan Area,Media Production,sent road map article|Sent sales process blog,NaN,NaN,"[sent road map article, Sent sales process blog]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,id.65853043,2021/04/14 15:54:10,https://www.linkedin.com/in/tyron-dew-4970791a,https://www.linkedin.com/sales/people/ACwAAAPs...,https://media-exp1.licdn.com/dms/image/C4D03AQ...,1,Tyron,,Dew,89,...,dew.tyron@yahoo.com,919-400-0318,,,"Raleigh, North Carolina, United States",Consumer Services,🦆-default-invited|Sent sales process blog,NaN,NaN,"[🦆-default-invited, Sent sales process blog]"
526,id.20478405,2021/04/14 15:55:32,https://www.linkedin.com/in/edward-morris-b19a366,https://www.linkedin.com/sales/people/ACwAAAE4...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Edward,,Morris,1274,...,edward@lynxworkflow.com,,,EdCanary,"Syracuse, New York, United States",Research,sent road map article|Sent promote or fire art...,NaN,NaN,"[sent road map article, Sent promote or fire a..."
527,id.161171344,2021/04/14 15:56:53,https://www.linkedin.com/in/rachaelstults,https://www.linkedin.com/sales/people/ACwAAAmb...,https://media-exp1.licdn.com/dms/image/C4E03AQ...,1,Rachael,,Stults,39,...,stultsrachael@yahoo.com,,,,Greater Philadelphia,Pharmaceuticals,🦆-default-invited|Sent sales process blog,NaN,NaN,"[🦆-default-invited, Sent sales process blog]"
528,id.123443746,2021/04/14 15:58:15,https://www.linkedin.com/in/stephen-daire-42a4...,https://www.linkedin.com/sales/people/ACwAAAdb...,https://media-exp1.licdn.com/dms/image/C5603AQ...,1,Stephen,,Daire,1526,...,sadaire@proteangistsolutions.com,6072875991,,DhDair,New York City Metropolitan Area,Think Tanks,|🦆-default-invited|sent road map article|Sent ...,NaN,NaN,"[, 🦆-default-invited, sent road map article, S..."
529,id.182513148,2021/04/14 15:59:38,https://www.linkedin.com/in/carey-camacho-0501...,https://www.linkedin.com/sales/people/ACwAAArg...,,1,Carey,,Camacho,174,...,carey@microtechsol.com,650-651-3076,,,"Burlingame, California, United States",Biotechnology,|🦆-default-invited|Sent sales process blog,NaN,NaN,"[, 🦆-default-invited, Sent sales process blog]"

In [23]:
conversation=first['My Tags'].str.contains('conversation')

In [24]:
first[conversation]

Empty DataFrame
Columns: [id, VisitTime, Profile, SalesProfile, Picture, Degree, First Name, Middle Name, Last Name, Connections, Summary, From, Title, Company, CompanyProfile, CompanyWebsite, Email, Phone, IM, Twitter, Location, Industry, My Tags, My Notes, Unnamed: 24, Tags]
Index: []

[0 rows x 26 columns]